# Generated by Django 4.1.7 on 2023-03-13 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tgbot.event_numb_generator
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_one_c', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_number', models.CharField(default=tgbot.event_numb_generator.event_numb_generator, max_length=15, unique=True, verbose_name='Номер заявки')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 14, 16, 3, 43026), verbose_name='Дата создания')),
                ('event_topic', models.CharField(default='Событие <django.db.models.fields.CharField> из телеграма', max_length=250, verbose_name='Тема события')),
                ('event_description', models.TextField(blank=True, null=True, verbose_name='Описание события')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_one_c.client', verbose_name='Клиент')),
            ],
        ),
    ]
