# Generated by Django 4.1.7 on 2023-03-13 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_tgevent_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgevent',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 15, 20, 10, 843785), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tgevent',
            name='event_number',
            field=models.CharField(default='БР-0001', max_length=15, unique=True, verbose_name='Номер заявки'),
        ),
    ]
