# Generated by Django 4.1.7 on 2023-03-13 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Полное наименование')),
                ('INN', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ИНН Физ/Юр лица')),
                ('status', models.CharField(choices=[('COMP', 'Компания'), ('PRIV', 'Частное лицо/ИП'), ('BUDGET', 'Бюджетное учреждение')], default='COMP', max_length=50, verbose_name='Тип пользователя')),
            ],
        ),
    ]
